TRUNCATE TABLE log;
TRUNCATE TABLE comentarios;
TRUNCATE TABLE categorias;
TRUNCATE TABLE listacategorias;
TRUNCATE TABLE valoraciones;
TRUNCATE TABLE fotos;
TRUNCATE TABLE recetas;
TRUNCATE TABLE usuarios;